# -*- coding: utf-8 -*-
"""ManipulationLAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jVURENhPgqak05JpoH3_M2zsYA7lCB-h
"""

!pip install lasio

import pandas as pd
import matplotlib.pyplot as plt
import lasio

las = lasio.read("/content/sample_data/DataLas1.2/2000.las")

las.sections.keys()

las.sections['Version']

for item in las.sections['Well']:
    print(f"{item.descr} ({item.mnemonic}): \t\t {item.value}")

las.well.WELL.value

for curve in las.curves:
    print(curve.mnemonic)

for count, curve in enumerate(las.curves):
    print(f"Curve: {curve.mnemonic}, \t Units: {curve.unit}, \t Description: {curve.descr}")
print(f"There are a total of: {count+1} curves present within this file")

well = las.df()

well.head(3)

well.describe()

well.info()

well.plot()

well.plot(y='PS')

well.to_csv("/content/sample_data/DataLas1.2/ExportCSV/2000.csv")

dataLas = pd.read_csv("/content/sample_data/DataLas1.2/ExportCSV/2000.csv")
dataLas.shape

dataLas.head(3)